[window]
opacity = 0.0

[font]
size = 12.0

[font.normal]
family = "Hack"

[colors.primary]
background = '#000000'
foreground = '#ffffff'

[colors.cursor]
text = '#000000'
cursor = '#dddddd'

[colors.normal]
black   = '#000000'
red     = '#ff0000'
green   = '#00ff00'
yellow  = '#ffff00'
blue    = '#0088ff'
magenta = '#ff00ff'
cyan    = '#00ffff'
white   = '#aaaaaa' 

[colors.bright]
black   = '#555555'
red     = '#ff8888'
green   = '#88ff88'
yellow  = '#ffff88'
blue    = '#55aaff'
magenta = '#ff88ff'
cyan    = '#88ffff'
white   = '#ffffff' 
  
